[package]
name = "onnx_on_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
protobuf-parse = "3.7.1"
prost = "0.13.4"

[build-dependencies]
protobuf = "3.7.1"
protobuf-codegen = "3.7.1"
protoc-bin-vendored = "3.1.0"
prost-build = "0.13.4"